name: Run tests

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
      
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: julia-actions/setup-julia@v1
      - name: Install dependencies and Test
        run: |
          export JULIA_PKG_PRECOMPILE_AUTO=0
          julia --threads 4 -e 'using Pkg                                                   
                    Pkg.activate(".")
                    Pkg.add(url="https://github.com/NilsNiggemann/SpinFRGLattices.jl")
                    Pkg.test()'

                                
      - name: Formatting Check
        run: |
          julia -e 'using Pkg
                    Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter 
                    @assert format(".") "Code not properly formatted!"'
